### ISSUE TITLE
Missing Recipes

### ISSUE THREAD

**Issue by WenXin20** [DoubleDoorDevelopment/Lumberjack#10]
I noticed that modded lumber axes couldn't be crafted, even multiple mods that add that material, for example copper.

**Comment by Claycorp** [comment]
Check the log ;)
All the axes that fail anything will get spit out with why. 99% of the time it's because the repair material isn't set, thus the mod doesn't know what to make the recipe from as everything is automatic. (Other than the textures getting created.) If you wish to make the axes you can use D3Core to set a repair material or use a crafting editor to set it yourself.

**Comment by WenXin20** [comment]
Ok, thanks

**Comment by WenXin20** [comment]
Ok, thanks

**Comment by Drakray** [comment]
The log file talk about a materials.json files, but I can't seems to find it :/
Where is it supposed to be?

**Comment by dries007** [comment]
[I've written a paragrahp in the D3Core readme about this.](https://github.com/DoubleDoorDevelopment/D3Core)

**Comment by Drakray** [comment]
Sorry I overlooked that lol :/

**Comment by dries007** [comment]
I wrote that just now :smile:

**Comment by Drakray** [comment]
this explain that XD

**Comment by Drakray** [comment]
is there a way to define oreDict entry as ItemStack?

**Comment by dries007** [comment]
No, that is impossible. (Forge doen't account for that)

**Comment by Drakray** [comment]
ok, thanks

**Comment by Drakray** [comment]
can I make multiple <Material Name> entry with different ItemStack then?, like
`
"BASEMETALS_TIN": "basemetals:tin_ingot 0 1",
"BASEMETALS_TIN": "mi:tin_ingot 0 1",
`

**Comment by dries007** [comment]
No, you can only have one.

**Comment by Drakray** [comment]
okidok

**Comment by Drakray** [comment]
The more you know, you don't need to have multiple, just one makes all the item that share oreDict to be usable in recipe

**Comment by dries007** [comment]
I think my code automatically does ore dict converting, but I forgot about that part. You could always use a recipe editor ofc.

**Comment by WenXin20** [comment]
How do I find the correct material name, for example, with FunOres mod?

**Comment by dries007** [comment]
Look for this line in your log file: 
`New LumberAxe {0} ({1}) From ...`
-  `{0}` is the `toolMaterial` (this is the correct name to put in the D3Core materials.json file)
- `{1}` is the `materialName` (this is the 'normalized' name, used to create the items and find the right texture)

**Comment by WenXin20** [comment]
Thanks
