### ISSUE TITLE
Support for Silent's Gems Mod?

### ISSUE THREAD

**Issue by WenXin20** [DoubleDoorDevelopment/Lumberjack#12]
Silent's Gems Mod adds axes, but lumberjack doesn't seem to show a missing texture for these materials, such as topaz, ruby, or onyx.

**Comment by dries007** [comment]
So they don't show up at all ingame?

**Comment by WenXin20** [comment]
Yes
It's forge 2073,
Silent's Gems 2.0.28-66, &
Silent's Lib 1.0.12-20

**Comment by dries007** [comment]
It looks like SilentGems is using the vanilla diamond material. That is something they should fix on there end, sorry.

**Comment by WenXin20** [comment]
Ok
