### ISSUE TITLE
Actually Additions Lumberaxes

### ISSUE THREAD

**Issue by WenXin20** [DoubleDoorDevelopment/Lumberjack#13]
They no longer show up
Actually Additions r60
Forge 2073

**Comment by Claycorp** [comment]
Do you remember what versions it did work with? I tested a bunch of different Lumberjacks and Actually Additions and couldn't get any to show up on any version.

**Comment by WenXin20** [comment]
Maybe r57? I'm not sure. I changed worlds since I last had them.

**Comment by drakray** [comment]
i'm not sure if this can be relevant, but in ActuallyAdditions, azes are named actuallyadditions:itemAxe(material)(*color), with item before Axe
