### ISSUE TITLE
[Bug] Material.json not taking some entry

### ISSUE THREAD

**Issue by drakray** [DoubleDoorDevelopment/Lumberjack#14]
namely:
"MANASTEEL": "botania:manaResource 0 1",
"B_ELEMENTIUM": "botania:manaResource 7 1",
"TERRASTEEL": "botania:manaResource 4 1",
"darkSteel": "enderio:itemAlloy 6 1"

they do not add recipe as they should(must add them manually with Crafttweaker, but I don't know if I can repair the lumberaxe then)

**Comment by dries007** [comment]
You put them in `materials.json` from D3Core right? (the title sais `Material.json`, missing the `s`). I wanna rule that out before I start digging :p

**Comment by drakray** [comment]
sorry for the title typo, here is my whole file, with txt appended to ext for upload
[materials.json.txt](https://github.com/DoubleDoorDevelopment/Lumberjack/files/629661/materials.json.txt)

**Comment by drakray** [comment]
nop, Manasteel not repairable
log line sontaining manasteel:
`Line 5957: [11:43:13] [Client thread/INFO] [Spark's Hammers/SparksHammers]: Spark's Hammers: Registering material Manasteel
Line 7694: [11:43:46] [Client thread/DEBUG] [FML/]: Item json isn't found for 'botania:storage#variant=manasteel', trying to load the variant from the blockstate json
Line 11217: [11:44:07] [Client thread/WARN] [D3Core/D3Core]: Skipped materials.json entry MANASTEEL=botania:manaResource 0 1 because mod botania is not loaded.
Line 11782: [11:44:10] [Client thread/INFO] [Lumberjack/Lumberjack]: LumberAxe manasteel without recipe! Ask the mod author of MANASTEEL for a ToolMaterial repairStack OR use D3Core's materials.json file to set it yourself.
Line 11783: [11:44:10] [Client thread/INFO] [Lumberjack/Lumberjack]: New LumberAxe MANASTEEL (manasteel) From axe botania:manasteelAxe
Line 12642: [11:44:12] [Client thread/WARN] [Actually Additions/actuallyadditions]: Couldn't add 2571 Crusher Recipes automatically, either because the inputs were missing outputs, or because they exist already: [oreGold, oreIron, oreLapis, oreDiamond, oreRedstone, oreEmerald, oreQuartz, oreCoal, oreCopper, oreTin, oreSilver, oreLead, oreNickel, orePlatinum, oreAluminium, oreAluminum, oreZinc, oreTitanium, orepig, orefish, orecow, orechicken, orerabbit, oresheep, oresquid, orebat, orezombie, oreskeleton, orecreeper, orespider, oreenderman, oreslime, orewitch, orepigman, oreghast, oremagmacube, orewither, oreblaze, oreguardian, oreArdite, oreCobalt, oreOsmium, oreEssence, oreSteel, gemEnderBiotite, oreMercury, oreAdamantine, oreStarsteel, oreColdiron, gemRuby, oreRuby, gemPeridot, orePeridot, gemTopaz, oreTopaz, gemTanzanite, oreTanzanite, gemMalachite, oreMalachite, gemSapphire, oreSapphire, gemAmber, oreAmber, ingotManasteel, ingotTerrasteel, ingotElvenElementium, ingotDawnstone, ingotElectricalSteel,...
`

**Comment by drakray** [comment]
after a couple of test, it seems like only BaseMetal ingot can repair Copper and Steel, even if I have 6 source of each(mot much of a problem as I normalize to BM, but still)

**Comment by drakray** [comment]
After more testing, ManaSteel is not repairable in the Anvil, but is still fusionnable with another lumberaxe, as are all

**Comment by dries007** [comment]
Its possible that this is one of the limitations on repair materials and meta data.
Minecraft is weird. It doesn't properly support metadata based repair materials in all scenarios.

**Comment by drakray** [comment]
that makes sense as they are the only one with metadata != 0
if possible, a good workaround for that would be using oreDict, but I think that's limited too

**Comment by dries007** [comment]
There is no way to use the oredict here.
Original MC uses an Item (not a stack) so no metadata, Forge already added the ItemStack (but then doesn't seem to fix all of the bare item uses). Making it oreDict would break that even further.
Since most people use Minetweaker, I decided not to add more hacks to do that.

**Comment by drakray** [comment]
only other way would be to hard code compatibility, or mark them as "must use CraftTweaker and repair by crafting"

**Comment by dries007** [comment]
You can't even really hardcode it, unless I basically add mini-minetweaker by adding recipe sync across server - client. (Since the server can have materials set/not set that the client doesn't, thus adding/removing recipes). I could add a warning about all of this to the log.

**Comment by drakray** [comment]
I think just a mention in README.md could be enough, trying to limit log size lol
Other than those technicallity, I think we can close this, as it is a Vanilla Limitation™
onward to #13 then :D

**Comment by dries007** [comment]
yea, I don't like log spam either. I'll make it sum up the elements in one line.
