### ISSUE TITLE
(1.11.2)textures dont render correctly when using mystical agriculture resources/actually additions

### ISSUE THREAD

**Issue by SDUBZ** [DoubleDoorDevelopment/Lumberjack#19]
as shown below:

![2017-03-18_19 49 21](https://cloud.githubusercontent.com/assets/14084377/24070572/65dc51b8-0c14-11e7-9c0a-6935ea4b075d.png)

mystical ag: mysticalagriculture[1.11.2]-1.4.4a
lumberjack: Lumberjack-1.11.2-1.3.1.48
actually additions: ActuallyAdditions-1.11.2-r106

**Comment by Claycorp** [comment]
They are missing textures as they never have been made. I'll add it to the list on #9
