### ISSUE TITLE
1.10.2 Version

### ISSUE THREAD

**Issue by Rasip** [DoubleDoorDevelopment/Lumberjack#20]
The 1.11.2 Version doesn't load with minecraft 1.10.2. The 1.9.4 version (listed as 1.10.2 on curse) Won't load without D3Core which is only available for 1.11.2.

Scratch that, it is a bad link in the curse page. 
https://minecraft.curseforge.com/mc-mods/223569-curse-cobalt-web-forms-textfield
should be
https://minecraft.curseforge.com/projects/d3core

**Comment by dries007** [comment]
That's because CurseForge changed the URL system, but didn't actually update the links on its pages automatically. @Claycorp should probably have a look around some day to update them.

**Comment by Claycorp** [comment]
Fixed. I'll add cleaning up and fixing all the curseforge pages to my todo list.
