### ISSUE TITLE
When used with Extra Utilities Mechanical User, only breaks one block

### ISSUE THREAD

**Issue by keithaw** [DoubleDoorDevelopment/Lumberjack#21]
I'm also seeing the same thing using the tool in progressive automation's tree chopper.  Does this tool only work if used by a player?

Using Version 1.3.1.49 for 1.10 of lumberjack and version 1.3.3 of extra utilities 2.

**Comment by dries007** [comment]
euh... The block may not be using a fakeplayer, I think that's a requirement, but I'm not sure.
