### ISSUE TITLE
MC 1.12

### ISSUE THREAD

**Issue by hron84** [DoubleDoorDevelopment/Lumberjack#22]
Could you please investigate if 1.12 is potentially can get this mod? It would perfectly fit my near-vanilla pack.

**Comment by DrDarkfire** [comment]
I second that. I would have the need for that my 1.12 Packs

**Comment by spikespaz** [comment]
I'm already working on a 1.12 port. Once I've finished it I'll open a pull request here, it looks like this repo is mostly inactive.

https://github.com/essentialmc/lumberjack

**Comment by dries007** [comment]
I have not looked into porting to 1.12 yet, I doubt it's even possible. Hence why no replies yet.
I'm glad someone else is, because it was low on my priority list and I unfortunately have little time.

**Comment by spikespaz** [comment]
@dries007 How does your versioning scheme work?

**Comment by dries007** [comment]
I don't increment versions if it's a straight port from one MC version to the next (with equal features).
If the port required significant changes, or the config has changed, I increment, depending on how severe the breakage, it's minor or patch.

I usually reserve major version changes for when a complete rewrite is required or when I feel the changes with the previous version is so great, it might as well be a new mod.

Oh and jar files should always be `<MC>-<Version>[.<BuildNR>]`.

**Comment by spikespaz** [comment]
@dries007 I see D3Core has been updated to 1.12, however your maven repo results in a 404.

http://doubledoordev.net/maven

**Comment by dries007** [comment]
Maven is dead, I recommend doing it like [JsonLootBags](https://github.com/DoubleDoorDevelopment/JsonLootBags).

**Comment by Claycorp** [comment]
There is a limited 1.12 version available now, Closing this.
