### ISSUE TITLE
1.4.0 for 1.12 causes the pack to crash.

### ISSUE THREAD

**Issue by DrDarkfire** [DoubleDoorDevelopment/Lumberjack#26]
My pack appears to crash on this 1.4.0 version of lumberjack, and starts up just fine without it. Here's the crash report: https://pastebin.com/k62XN33c

**Comment by Claycorp** [comment]
AH FUCK, Forgot the AT stuff in the build.gradle.... Give me ~10 minutes and I'll get this fixed.

**Comment by Claycorp** [comment]
Fixed and uploaded, Just waiting for approval.
Sorry bout that, Them sneaky AT's get me every time....

**Comment by DrDarkfire** [comment]
It's all good. Glad I helped you catch it, instead of going whelp that didn't work.
