### ISSUE TITLE
"Use All Materials" config option doesn't work.

### ISSUE THREAD

**Issue by WenXin20** [DoubleDoorDevelopment/Lumberjack#27]
Forge v14.23.5.2810-1.12.2
Lumberjack v1.4.0

Before version 1.4.0 came out, I was able to change this option to true to allow other materials to be used. Now the option doesn't work at all when changed to true, and previously existing axes are now missing in my world. 

The mod Actually Additions adds its own axes that lumberjack doesn't recognize, but the materials are recognized by this mod if this config option is on, and now that doesn't work at all. (There are textures for them in this mod)

Thanks for looking into this!

**Comment by Claycorp** [comment]
Sorry for the super late reply, It should work now. Just need to wait for CF to approve it.

**Comment by WenXin20** [comment]
Ok, thanks!
