### ISSUE TITLE
Insane Attack Speed?

### ISSUE THREAD

**Issue by LogicEngineer** [DoubleDoorDevelopment/Lumberjack#29]
Just my personal opinion but I really think the attack speed of these axes should be toned down to be on the level of most other axes. Why can I swing a diamond lumber axe 12 times faster than a regular diamond axe?

**Comment by Claycorp** [comment]
What version..?

**Comment by LogicEngineer** [comment]
SORRY. Version 2.0.0

**Comment by Claycorp** [comment]
Ah, 1.14
I'll take a look at it some time soon. It needs a good chunk of work outside of just the attack speed as it's missing the key feature of making axes from other materials!

**Comment by Claycorp** [comment]
Fixed in 2.1.2 for 1.16.
If this needs to be backported open a new issue please.
