### ISSUE TITLE
Initializing game  java.lang.ArrayIndexOutOfBoundsException: 112

### ISSUE THREAD

**Issue by accessdenied0** [DoubleDoorDevelopment/Lumberjack#3]
Dear DoubleDoorDevelopment,

I got sadly an issue with your mod, but I don't quite know where it came from...

Here i got the log for you guy: http://pastebin.com/1s0czWH9

access denied

**Comment by accessdenied0** [comment]
Hi dries007,

wow, you are fast... thank you for the quick resolution. Sorry that I ask here, but is there a possibility to download or compile this quick fix? I surely wanted to use your great mod...

access_denied

**Comment by dries007** [comment]
Our builds get autobuild on commits

http://www.doubledoordev.net/?p=modlist&mod=Lumberjack

**Comment by accessdenied0** [comment]
Thanks ^^
