### ISSUE TITLE
[1.14 ] item name tooltip bug

### ISSUE THREAD

**Issue by Crissaegrem** [DoubleDoorDevelopment/Lumberjack#30]
it show the full real name or meta is it called.
even on inventory, name stays the same.

![lumberjack](https://user-images.githubusercontent.com/7549149/69973876-2bd9ec80-155f-11ea-8c1b-768a4a4ff5ec.png)

**Comment by Claycorp** [comment]
I can't replicate this with forge:1.14.4-28.1.107 in my dev environment, Assuming its not my issue. Feel free to open again if you can reproduce and provide more info.

**Comment by michalwa** [comment]
Having the same issue on Forge 1.14.4-28.2.0. The item names are missing both in JEI and regular inventory menus.

Mods installed:
 - LumberJack 2.0.0
 - Just Enough Items 6.0.0.27
 - Inventory Profiles 0.1.0-dev5
 - MaLiLib 0.10.0-dev.19
 - Backpacked 1.4.0
 - Obfuscate 0.4.1
 - MrCrayfish's Furniture Mod 7.0.0-pre15
 - MrCrayfish's Vehicle Mod 0.43.6
 - Enchantable 1.1.0
 - Mystical Wildlife 1.3.2
 - The Endergetic Expansion 1.2.0
 - Ambient Sounds 3.0.3
 - Biomes O' Plenty 1.14.4-9.0.0.259
 - VoxelMap 1.9.13
 - Create mc1.14-0.2.2a
 - More Ores in ONE 1.5

**Comment by Claycorp** [comment]
Fixed in 2.0.1 was a stupid mistake.
