### ISSUE TITLE
[1.16.x] Lumberaxes aren't named properly

### ISSUE THREAD

**Issue by MichaelSixtyFour** [DoubleDoorDevelopment/Lumberjack#34]
Hello! Just playing with this mod in 1.16.1 and it looks like the lumberaxes aren't properly pulling the name of the axe. [Here is a screenshot](https://i.imgur.com/p1HymR2.png) showing this.

Thanks!

**Comment by Claycorp** [comment]
uhh, well...
Not sure what's going on here. I can confirm the names are broke outside of the dev environment only.
There isn't any errors in the log and I'm not aware of any changes that would break this?

I'll need to look a bit deeper into it.

**Comment by Claycorp** [comment]
I overlooked the change on the lang file names in 1.13/1.14 when they changed to JSON.
Why this wasn't throwing an error or was working in the dev space I couldn't tell you but it's fixed in 2.1.1 and is the same problem as #30 

Builds will be on CF shortly.

**Comment by MichaelSixtyFour** [comment]
I was just looking through the files on my own fork and renamed the .json file and solved it as well, glad to see it is fixed!

**Comment by Claycorp** [comment]
I feel 100% dumb on that one lol
