### ISSUE TITLE
[1.16][TreeSupport] Nether stuff

### ISSUE THREAD

**Issue by drakray** [DoubleDoorDevelopment/Lumberjack#36]
Hi there, could it be possible to add support for custom stuff, like the [OhTheBiomeYoullGo](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go) Nether/End Tree and the vanilla Warped and Crimson?

Otherwise maybe adding a JSON config to be able to add the log/leaves/fruit ourselves?

Thank you for the consideration :)

**Comment by spicehoarder** [comment]
I second this, I'd like a config. That way we don't have to pester the dev, and we can add modded wood ourselves.

**Comment by Claycorp** [comment]
Ah yes, Sorry I forgot to reply on this ages ago when I was looking into it...

I've been waiting for Forge to get there tooling for the 1.16+ version so it's easier to work with. I tried to look into this some and clearly the new "woods" are not woods at all....

I do plan on changing the chopping mechanic to support tags so you can either use the material based system like it currently does or just tags. (or both if you really want!)

Also, pester me all you want. It's my fault it's not working right and I really should be taking better care of all these mods.
