### ISSUE TITLE
Item tags for lumberaxes?

### ISSUE THREAD

**Issue by hammertater** [DoubleDoorDevelopment/Lumberjack#37]
It would be very helpful if there were a shared item tag for lumberaxes. Something like `#lumberjack:lumberaxes`.

I care because I'm maintaining a mod that adds a tree-chopping mechanic, and to prevent conflicts, I'd like to blacklist modded items that have their own tree-chopping mechanics. Since your items are created dynamically, the surest way to detect them would be to check item tags.

**Comment by Claycorp** [comment]
They currently are not made dynamically but yes, I can add a tag. There's a bunch of other things I need to do also so I'm not sure when I'll get around to it.

**Comment by hammertater** [comment]
Sounds good! No rush 👍

**Comment by hammertater** [comment]
Thanks a bunch!
