### ISSUE TITLE
Missing Textures & item.lumberaxe.name issue

### ISSUE THREAD

**Issue by Jfluffy** [DoubleDoorDevelopment/Lumberjack#4]
The lumber axes that are made out of metals from other mods such as Bronze, Thaumium and Mana Steel are missing their texture (they appear as a pink and block checkered box) and display their file name stead of the name of the item.

**Comment by Claycorp** [comment]
Well.. Thats the first time I have ever heard of axes being auto-generated. 

Bronze should work as there is a texture for it. What mod adds the bronze? Perhaps it's just a derp.

**Comment by Jfluffy** [comment]
I apologize for the delay in responding. I deleted the build that I was having the problems with and I can't remember which mod was the one that added bronze. 

However, I did some experimenting and found causational relationship with the extra axes and the Expanded Armory mod(link to their curse page provided below. I would hypothesize that EArmory it looks at the ore dictionary for what weapons exist(thus looking at your axes) to make mod metal version of them.

http://www.curse.com/mc-mods/minecraft/228071-expanded-armory

**Comment by Claycorp** [comment]
Hey delays are fine. If we can get it fixed is what matters.

Oredictionary does not apply to tools like that but Lumberjack itself looks for tool materials to make more axes from. I have never seen them be created as the method we use is quite often ignored sadly. 

A quick look at Expanded Armory it seems to add some of those materials for the things it adds. I have a slight hunch some of these are not craftable or useable. I will do some testing and see if i can pinpoint why at least the bronze isn't being applied as the texture exists. The rest of them don't have textures. @Morton00000 can help with the textures.

**Comment by Jfluffy** [comment]
I see, that makes much more sense! So under normal circumstances, if Steel or Bronze is added to the game through a mod, your mod *should* add lumber axes of those material to the list of axes I can craft?
If so, it doesn't seem to be recognizing the Tinker's Alloy(Bronze) from Thermal Foundation or Steel from Artifice or Railcraft in my testing environment. In my initial environment when I noticed the missing textures, it had a steel lumberaxe (it was named and textured just fine). I'll see if I can recreate that environment tomorrow to see if I can dig up anything that might be helpful for you.

**Comment by Claycorp** [comment]
Yeah there's a special list that we pull from. Its quite literally called "materials". Vanilla uses it and very few other mods do thus why I was surprised.

I know for a fact that TiCO, CoFH mods, Thaulmcraft, EnderIO, AE2, Biomes O' Plenty and Extra utils do not add new axes. 

Hope we can get this sorted out as it would be nice to see a few new axes out there!

**Comment by Jfluffy** [comment]
I still can't seem to recreate the instance in which I experience my initial issue with the untexture bronze axe, I also do not recall seeing a copper axe when I had the untextured bronze axe issue. I did however find that the Lumberaxe mod and Metallurgy seem to work well together, albeit lots of missing textures. The Vanilla materials along with the Bronze, Steel, Copper, Silver and Brass axes all were fine in name and texture. 

If you're looking for different materials to make axes out of, I think an axe made from the Falling Meteors material would make a great lumberaxe, given that Meteor tools have magnetization automatically on them. 

If these mods do not add their metals to this "materials" list, how does a mod like Tinker's Construct know when to have (for example) Thaumium components? Would TiCO have a hard coded boolean which checks to see if Thaumcraft is installed before adding those components?

**Comment by Claycorp** [comment]
I can get textures for Metallurgy also if you have a list that are missing. If not i can do it when i have time.

We don't make any axes the mod handles it all on its own. I don't think enchantments pass over.

The materials list isn't necessary you can add things without using it like most people do but it makes adding new types of tools/armour or whatever in harder because now you need to set all your own values for things like durability, harvest level and such..

**Comment by Jfluffy** [comment]
The axes made out of the following Metallurgy metal made are missing textures: <list> Inolashite, Angmallen, Electrum, Mithril, Carmot, Eximite, Celenegil, Ceruclase, Adamantine, Sanguinite, Ignatius, Orichalcum, Tartarite, Desichalkos, Amordrine, Quicksilver, Altarus, Midasium, Vulcanite, Oureclase, Platinum, Prometheum, Vyroxeres, Haderoth, Hepatizon, Kalendrite </list>

I guess it really comes down to if someone goes for a more monolithic or modular approach to what ever material their mod adds. This has certainly been enlightening and I appreciate the information you've provided.

**Comment by Claycorp** [comment]
I will send this off to @Morton00000 so we can get them filled in!

Yeah people who deal with just adding in a new item based off other mods could benefit tons from it. Just remember that I might not have explained everything perfectly but i did it to my best of my knowledge.

Keep enjoying our mods and let us know if anything happens!

**Comment by Jfluffy** [comment]
I have finally been able to recreate two scenarios in which the bronze axe(but also the steel axe as well) is unnamed and untextured using two different mods that add metals, but do not add to the list which your mod pulls from. 

Both having D3 Core, Lumberjack, Balkin's Weapon and Expanded Armory
The first combination has CoHF Core & Thermal Foundation
The second being Boilerplate & Steam Craft

The file names seem off as well, in the first combination the bronze axe had the name "item.lumberaxeTf:bronze.name" and the steel axe the name "item.lumberaxeEa:steel.name".
Both axes seemed to functioned properly but I think it is safe to say that the problem mod in this case is indeed Expanded Armory.

**Comment by Claycorp** [comment]
It is fixed now. It will be up on curseforge in a second. 
Yay!

**Comment by mallrat208** [comment]
That's my bad, I'm sorry.

I was tired of adding the repair material for each weapon I was going to use so I ah.. 'fixed' the tool materials that lacked a repair itemstack.

**Comment by Claycorp** [comment]
Hey at least someone is using the materials properly!

It wasn't necessarily your problem it was just with how things were named. Others could have added prefixes too but this case wasn't caught. It all works fine now :D
