### ISSUE TITLE
Unnamed, untextured axes added by mod via materials list

### ISSUE THREAD

**Issue by Jfluffy** [DoubleDoorDevelopment/Lumberjack#5]
Hello again, "Shadow World" adds more axes via the materials list that are without names and textures.
the materials are: "Azurite" "Shadow" "Blood Stone" "Umarite" "Gamandium" "Soul" "Angel"

**Comment by Claycorp** [comment]
Can you push F3+H and take a screenshot while hovering over the item or write it down here.
Thanks!

**Comment by Jfluffy** [comment]
![2015-05-15_15 12 51](https://cloud.githubusercontent.com/assets/8961563/7660071/fb2ca6f4-fb14-11e4-97df-de3e3df4b909.png)
![2015-05-15_15 12 52](https://cloud.githubusercontent.com/assets/8961563/7660070/fb2bda6c-fb14-11e4-84c9-08968b1e57e8.png)
![2015-05-15_15 12 53](https://cloud.githubusercontent.com/assets/8961563/7660072/fb2d4f64-fb14-11e4-9d37-1828834c6c7b.png)
![2015-05-15_15 12 55](https://cloud.githubusercontent.com/assets/8961563/7660075/fb2e3bc2-fb14-11e4-9cea-0445947987f0.png)
![2015-05-15_15 12 56](https://cloud.githubusercontent.com/assets/8961563/7660073/fb2e2880-fb14-11e4-8373-6ebced99ccd7.png)
![2015-05-15_15 12 57](https://cloud.githubusercontent.com/assets/8961563/7660074/fb2e535a-fb14-11e4-8ab0-3c5eac83b3da.png)
![2015-05-15_15 12 58](https://cloud.githubusercontent.com/assets/8961563/7660076/fb37ddf8-fb14-11e4-8ffe-b45aa1305659.png)

**Comment by dries007** [comment]
@Morton00000 Here is some work for you :p

**Comment by Jfluffy** [comment]
@Morton00000 Sorry If I am causing you to be overworked! >_<

**Comment by dries007** [comment]
I'm closing this in favor of #9 as it's unlikely 1.7 stuff will ever be added still.
