### ISSUE TITLE
Crash with "Timber:lumberaxeBronze has been registered twice"

### ISSUE THREAD

**Issue by gl0x** [DoubleDoorDevelopment/Lumberjack#6]
I'm assuming this is because of multiple types of bronze? Here's my log:

http://pastebin.com/N62aN6i2

**Comment by dries007** [comment]
Yea, Most mods rename there materials to something like `ic2_bronze`, I'll add checks to prevent this.

**Comment by dries007** [comment]
What version of the mod are you using? A check like this has been added for a long wile now.

**Comment by gl0x** [comment]
I was using the latest 1.7.10 version on Curse, 1.1.0.21

**Comment by dries007** [comment]
Are you absolutely sure about that?
The line ` at net.doubledoordev.timber.items.ItemLumberAxe.<init>(ItemLumberAxe.java:71)` indicates a really old version, from before the mod was renamed to Lumberjack.
Can you do me a favor and download it fresh from curse?

**Comment by Claycorp** [comment]
'Timber{1.0} [Timber] (Lumberjack-1.7.10-1.0.0.2.jar)'

100% outdated and not the latest version from curse.
