### ISSUE TITLE
Lumberjack{1.2.0.33} crashes dedicated Forge 1.10.2 build 2007 on startup

### ISSUE THREAD

**Issue by kreezxil** [DoubleDoorDevelopment/Lumberjack#8]
Issue:  Lumberjack{1.2.0.33} crashes dedicated Forge 1.10.2 build 2007 on startup

crash report:
https://gist.github.com/f01516948e64a6807a472784f1c345a5

fml server latest:
https://gist.github.com/e88c8ec0b33f4bd4ad77f69c3c1293cd

**Comment by dries007** [comment]
Could you test with https://jenkins.dries007.net/job/Lumberjack/34/ quick?

**Comment by dries007** [comment]
If could post the FML latest again if you get it started, it should tell me what mod is causing the issue and I can take measures to prevent it from happening/contact the author(s). Technically they are (99% sure) responsible for this issue, but I seem to be the only one using ToolMaterials in this way, so no one seems to notice :smile:

**Comment by dries007** [comment]
I'm working on a better fix, but builds since 34 will not crash; some axes will be missing though.
